/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author yrnsh
 */
public class ProgressBar extends java.applet.Applet {

    /**
     * Initializes the applet ProgressBar
     */
    public void init() {
        try {
            java.awt.EventQueue.invokeAndWait(new Runnable() {
                public void run() {
                    initComponents();
                }
            });
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the init() method to initialize the
     * form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        counter1 = new counter.Counter();
        counter2 = new counter.Counter();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        counter1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        add(counter1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 60, 50));

        counter2.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        add(counter2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, 60, 50));

        jButton1.setText("Java");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 90, 40));

        jButton2.setText("PHP");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, 80, 40));

        jProgressBar1.setStringPainted(true);
        add(jProgressBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, 300, 50));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Choose Your Favourite \nProgramming Languange!");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jLabel2.setText("Grey      = Java\n");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 130, -1));

        jLabel3.setText("White    = PHP");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 120, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        counter1.increment();
        int value1 = (int) counter1.getValue();
        int value2 = (int) counter2.getValue();
        int value3 = value1+value2;
   
        if (value2 == 0){
            jProgressBar1.setValue(value1);
        }
        else {
            jProgressBar1.setValue(value2);
        }
        jProgressBar1.setMaximum(value3);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        counter2.increment();
        int value1 = (int) counter1.getValue();
        int value2 = (int) counter2.getValue();
        int value3 = value1+value2;
          if (value1 == 0){
            jProgressBar1.setValue(value2);
        }
        else {
            jProgressBar1.setValue(value1);
        }
        jProgressBar1.setMaximum(value3);
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private counter.Counter counter1;
    private counter.Counter counter2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JProgressBar jProgressBar1;
    // End of variables declaration//GEN-END:variables
}
